owner: digital-teams
repo: status

sites:
  - name: Google
    url: https://www.google.com
    icon: https://www.google.com/favicon.ico
  - name: Cloudflare DNS over TLS
    url: https://cloudflare-dns.com
    icon: https://www.cloudflare.com/favicon.ico

status-website:
  links:
    - rel: stylesheet
      href: https://github.zshell.dev/fa/css/all.min.css
  themeUrl: https://status.zshell.dev/themes/night.css
  logoUrl: https://github.com/z-shell.png
  metaTags:
    - name: "robots"
      content: "noindex"
  css: "body { opacity: 1 }"
  theme: night
  #cname: demo.upptime.js.org
  baseUrl: /status
  name: Uptime
  introTitle: "<i class='fa-solid fa-chart-line'></i> Uptime Status"
  introMessage: "<i class='fa-brands fa-connectdevelop'></i> The open-source uptime monitor and status page."
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  #- name: Secret Site
  #  url: $SECRET_SITE
  #- name: API endpoint
  #  url: https://example.com/get-user/3?api_key=$MY_API_KEY
  #- name: API endpoint
  #  url: https://example.com/get-user/3
  #  headers:
  #   - "Authorization: Bearer $SECRET_SITE_2"
  #   - "Content-Type: application/json"
  #- name: API endpoint with data
  #  method: POST
  #  url: https://example.com/login
  #  headers:
  #    - "Content-Type: application/json"
  #  body: '{ "password": "hello" }'
